export const ZIMPSL_LIST_REQUEST = "ZIMPSL_LIST_REQUEST";
export const ZIMPSL_LIST_SUCCESS = "ZIMPSL_LIST_SUCCESS";
export const ZIMPSL_LIST_FAIL = "ZIMPSL_LIST_FAIL";
export const ZIMPSL_LIST_RESET = "ZIMPSL_LIST_RESET";

export const ZIMPSL_GAMEWEEKS_REQUEST = "ZIMPSL_GAMEWEEKS_REQUEST";
export const ZIMPSL_GAMEWEEKS_SUCCESS = "ZIMPSL_GAMEWEEKS_SUCCESS";
export const ZIMPSL_GAMEWEEKS_FAIL = "ZIMPSL_GAMEWEEKS_FAIL";

export const ZIMPSL_DETAILS_SUCCESS = "ZIMPSL_DETAILS_SUCCESS";
export const ZIMPSL_DETAILS_REQUEST = "ZIMPSL_DETAILS_REQUEST";
export const ZIMPSL_DETAILS_FAIL = "ZIMPSL_DETAILS_FAIL";

export const ZIMPSL_CREATE_REQUEST = "ZIMPSL_CREATE_REQUEST";
export const ZIMPSL_CREATE_SUCCESS = "ZIMPSL_CREATE_SUCCESS";
export const ZIMPSL_CREATE_FAIL = "ZIMPSL_CTREATE_FAIL";
export const ZIMPSL_CREATE_RESET = "ZIMPSL_CREATE_RESET";

export const ZIMPSL_EDIT_REQUEST = "ZIMPSL_EDIT_REQUEST";
export const ZIMPSL_EDIT_SUCCESS = "ZIMPSL_EDIT_SUCCESS";
export const ZIMPSL_EDIT_FAIL = "ZIMPSL_EDIT_FAIL";

export const ZIMPSL_UPDATE_REQUEST = "ZIMPSL_UPDATE_REQUEST";
export const ZIMPSL_UPDATE_SUCCESS = "ZIMPSL_UPDATE_SUCCESS";
export const ZIMPSL_UPDATE_FAIL = "ZIMPSL_UPDATE_FAIL";
export const ZIMPSL_UPDATE_RESET = "ZIMPSL_UPDATE_RESET";

export const ZIMPSL_DELETE_REQUEST = "ZIMPSL_DELETE_REQUEST";
export const ZIMPSL_DELETE_SUCCESS = "ZIMPSL_DELETE_SUCCESS";
export const ZIMPSL_DELETE_FAIL = "ZIMPSL_DELETE_FAIL";
export const ZIMPSL_DELETE_RESET = "ZIMPSL_DELETE_RESET";